name: finance_recorder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  image_picker: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2
  reorderable_grid_view: ^2.2.8
  toastification: ^1.0.2
  introduction_screen: ^3.0.3

  drift: ^2.28.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.28.1-dev.0
  build_runner: ^2.6.0-dev.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # Path to your app icon

flutter:
  uses-material-design: true

  # Adding the assets section
  assets:
    - assets/avatar.jpg

